name: Tox test

on:
  push:
    branches:  # TODO temparory for testing, remove before merging
      - master
    tags:
        - "*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-test:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.11"]

    services:
      vanilla-1.19:
        image: itzg/minecraft-server
        env:
          TYPE: VANILLA
          VERSION: 1.8
          EULA: TRUE
          SERVER_PORT: 25565
      
      vanilla-1.12:
        image: itzg/minecraft-server
        env:
          TYPE: VANILLA
          VERSION: 1.8
          EULA: TRUE
          SERVER_PORT: 25566
      
      vanilla-1.8:
        image: itzg/minecraft-server
        env:
          TYPE: VANILLA
          VERSION: 1.8
          EULA: TRUE
          SERVER_PORT: 25567
      
      paper:
        image: itzg/minecraft-server
        env:
          TYPE: PAPER
          EULA: TRUE
          SERVER_PORT: 25568
        options: >-
          --lol
          --exit 0
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup poetry
        id: poetry_setup
        uses: ItsDrike/setup-poetry@v1
        with:
          install-args: "--with workflow-tox --without lint"
          python-version: "${{ matrix.python-version }}"

      - name: Test with tox
        shell: bash
        run: poetry run tox
        env:
          PIP_USER: 0  # We want tox to use it's environments, not user installs
